### ISSUE TITLE
FST_ERR_SCH_MISSING_ID: Missing schema $id property

### ISSUE THREAD

**Issue by timvol** [ahmadnassri/node-oas-fastify#17]
I've a very simple json-file:

```js
{
    "openapi":"3.0.2",
    "info": {
        "title":"API Title",
        "version":"1.0"
    },
    "servers": [
        {"url":"https://api.server.test/v1"}
    ],
    "paths": {
        "/": {
            "get": {
                "description": "",
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                },
                "operationId": "getSomething"
            }
        }
    }
}
```

And the following source:

```js
  const spec = require('./package.json')
  const handler = {
    async getSomething(req, resp) {
      // do something
    }
  }
  fastify.register(require('oas-fastify'), { spec, handler })
  await fastify.listen()
```

So... I guess nothing special. But when I run the application, I'm getting the following error:

```
<PathRemoved>\node_modules\fastify\lib\schemas.js:27
    throw new FST_ERR_SCH_MISSING_ID()
          ^
FastifyError [Error]: Missing schema $id property
    at Schemas.add (<PathRemoved>\node_modules\fastify\lib\schemas.js:27:11)
    at Object.addSchema (<PathRemoved>\node_modules\fastify\fastify.js:469:20)
    at module.exports (<PathRemoved>\node_modules\oas-fastify\lib\plugin.js:8:12)
    at Plugin.exec (<PathRemoved>\node_modules\avvio\plugin.js:131:17)
    at Boot.loadPlugin (<PathRemoved>\node_modules\avvio\plugin.js:266:10)
    at Task.release (<PathRemoved>\node_modules\fastq\queue.js:140:16)
    at worked (<PathRemoved>\node_modules\fastq\queue.js:182:10)
    at <PathRemoved>\node_modules\avvio\plugin.js:269:7
    at done (<PathRemoved>\node_modules\avvio\plugin.js:201:5)
    at check (<PathRemoved>\node_modules\avvio\plugin.js:225:9) {
  code: 'FST_ERR_SCH_MISSING_ID',
  statusCode: 500
}
```

Any idea how I can fix this error? I'm using fastify 3.6.0, oas-fastify 1.3.4 and Node.js 14.0.0

**Comment by ahmadnassri** [comment]
I'm still not quite sure why fastify expects `$id` propertly, just just add it to the spec object:

```js
const spec = require('./spec.json')

// workaround for fastify
spec.$id = '$'

fastify.register(require('oas-fastify'), { spec, handler })
```
